// Le JEU et la FICHE des exemples d'exercice dans Chrome (/dev/exemple et /dev/exemple-corpus) et du calcul mental (exercice reporté) : réglages, changement de
// niveau, bonne et mauvaise réponse, suite et résultats, rejouer, fiche reproductible (Jouer → Imprimer → Jouer → Imprimer =
// même fiche ; « Nouvelle fiche » écrit la graine dans l'URL ; recharger la garde). Pas d'attente fixe : on attend un état de
// la page, et l'horloge est pilotée (page.clock) pour le délai de 1,6 s qui suit une bonne réponse.
// Les pages /dev n'existent que dans un site construit avec VITE_AVEC_DEV=1 (tests/lancer.mjs → TEST_URL_DEV) ou sur le
// serveur de dev :
//   TEST_URL=http://localhost:5173/ecole-primaire/ node tests/jeu-dev.test.mjs
import { lancerNavigateur, contexte, surveiller, verifier, nbEchecs, appDev } from './outils.mjs'

const nav = await lancerNavigateur()
const ctx = await contexte(nav)
const page = await ctx.newPage()
const erreurs = surveiller(page)
// « Blocked script execution in 'about:srcdoc' » : attendu. L'aperçu est un iframe sandbox SANS allow-scripts et la fiche ne contient
// aucun script ; c'est le script d'initialisation que Playwright (contexte(), page.clock) injecte dans chaque frame que le navigateur bloque.
page.on('console', m => { if (m.type() === 'error' && !/\/journal\?/.test(m.location().url ?? '') && !/Blocked script execution/.test(m.text())) erreurs.push(m.text().slice(0, 200)) })
await page.clock.install()

const ouvrir = async route => {
  await page.goto('about:blank')
  await page.goto(appDev(route))
  await page.waitForSelector('.cadre-exercice')
}
const actifs = cle => page.locator(`[data-reglage="${cle}"] .level-btn.active`).evaluateAll(l => l.map(b => b.dataset.valeur))
const cliquer = (cle, valeur) => page.locator(`[data-reglage="${cle}"] [data-valeur="${valeur}"]`).click()
const apercu = () => page.locator('iframe').evaluate(f => f.contentDocument?.documentElement?.innerHTML ?? '')
const attendreApercu = async () => { await page.waitForSelector('iframe'); await page.waitForFunction(() => !!document.querySelector('iframe')?.contentDocument?.querySelector('.entete')) }
const suivant = () => page.locator('.exercise-box .btn-primary')
const numeroQuestion = () => page.locator('.score-bar span').first().textContent()

// La réponse juste d'une question de l'exemple « suites » lue à l'écran : le terme qui manque, ou le pas
const reponseJuste = () => page.evaluate(() => {
  const suite = [...document.querySelectorAll('.suite > *')]
  const nombres = suite.map(e => (e.matches('.terme') ? Number(e.textContent) : null))
  const connus = nombres.map((n, i) => ({ n, i })).filter(x => x.n !== null)
  const pas = connus[1].n - connus[0].n
  const unPas = pas / (connus[1].i - connus[0].i)
  const trou = nombres.indexOf(null)
  const regle = !document.querySelector('.suite .exercise-input')
  return regle ? Math.abs(unPas) : connus[0].n + unPas * (trou - connus[0].i)
})
const saisir = async n => { await page.locator('.exercise-input').fill(String(n)); await page.keyboard.press('Enter') }

console.log('Exemple simple : réglages et niveau')
await ouvrir('/dev/exemple')
verifier((await actifs('niveau'))[0] === 'cp', 'ouvre au niveau par défaut (CP)')
verifier(await page.locator('[data-reglage="pas"] [data-valeur="5"]').textContent().then(t => t.includes('bonus')), 'le CP propose 5 en bonus (marqué)')
await cliquer('pas', '1')   // un pas de moins coché : la liste se modifie
verifier(!(await actifs('pas')).includes('1') || (await actifs('pas')).length > 0, 'au moins une valeur reste cochée')
await cliquer('niveau', 'ce1')
verifier(JSON.stringify(await actifs('pas')) === '["2","5","10","100"]', 'CE1 : un choix multiple reprend les défauts du niveau')
await cliquer('niveau', 'cp')
verifier((await actifs('pas')).every(v => ['1', '2', '10'].includes(v)), 'retour au CP : seuls les pas du programme sont cochés (le bonus 5 ne suit pas)')
await cliquer('nbQ', '5')
await cliquer('exercices', 'complete')

console.log('Exemple simple : partie')
await page.locator('.actions .btn-primary').click()
await page.waitForSelector('.score-bar')
verifier((await numeroQuestion()).includes('1'), 'la partie commence à la question 1')
// 1re : une mauvaise réponse
await saisir((await reponseJuste()) + 7)
await page.waitForSelector('.feedback.erreur')
verifier(await page.locator('.feedback.erreur').count() === 1, 'mauvaise réponse : retour « erreur »')
await suivant().click()
await page.waitForFunction(() => document.querySelector('.score-bar span')?.textContent?.includes('2'))
// 2e : une bonne, puis l'horloge avance (délai avant la suite)
await saisir(await reponseJuste())
await page.waitForSelector('.feedback.ok')
verifier(await page.locator('.feedback.ok').count() === 1, 'bonne réponse : retour « ok »')
await page.clock.runFor(2000)
await page.waitForFunction(() => document.querySelector('.score-bar span')?.textContent?.includes('3'))
verifier(true, 'une bonne réponse passe seule à la question suivante')
for (let i = 3; i <= 5; i++) {
  await saisir(await reponseJuste())
  await page.waitForSelector('.feedback.ok')
  await page.clock.runFor(2000)
}
await page.waitForSelector('.resultats-jeu')
verifier((await page.locator('.result-score').textContent()).includes('4') && (await page.locator('.result-score').textContent()).includes('5'), 'résultats : 4 / 5 (une erreur)')
verifier(await page.locator('.resultats-jeu .btn-primary').count() === 1, 'Rejouer disponible')
await page.locator('.resultats-jeu .btn-primary').click()
await page.waitForSelector('.score-bar')
verifier((await numeroQuestion()).includes('1'), 'rejouer : une nouvelle partie, question 1')
await page.locator('.btn-quitter').click()
await page.waitForSelector('.cadre-exercice')
verifier((await actifs('nbQ'))[0] === '5', 'quitter : retour aux réglages, ils sont gardés')

console.log('Exemple simple : fiche reproductible (graine)')
await page.locator('.modes button').nth(1).click()
await attendreApercu()
const fiche1 = await apercu()
verifier(/class="suite"/.test(fiche1), 'l\'onglet « Imprimer » montre la fiche')
await page.locator('.modes button').nth(0).click()
await page.waitForSelector('.actions .btn-primary')
await page.locator('.modes button').nth(1).click()
await attendreApercu()
verifier(await apercu() === fiche1, 'Jouer → Imprimer → Jouer → Imprimer : la même fiche')
const urlAvant = page.url()
await page.locator('.apercu-impression .btn-ghost, button:has-text("ouvelle")').first().click()
await page.waitForFunction(av => location.href !== av, urlAvant)
// l'aperçu suit l'URL : on attend qu'il ait changé (état de la page, pas une durée)
await page.waitForFunction(av => (document.querySelector('iframe')?.contentDocument?.documentElement?.innerHTML ?? av) !== av, fiche1)
const fiche2 = await apercu()
verifier(/graine=\d+/.test(page.url()) && fiche2 !== fiche1, '« Nouvelle fiche » : une autre fiche, graine écrite dans l\'URL')
const lien = page.url()
await page.goto('about:blank')
await page.goto(lien)
await attendreApercu()
verifier(await apercu() === fiche2, 'recharger le lien redonne la même fiche')
await page.goto(appDev('/dev/exemple?mode=imprimer&graine=12345'))
await attendreApercu()
const f12345 = await apercu()
await page.goto('about:blank')
await page.goto(appDev('/dev/exemple?mode=imprimer&graine=12345'))
await attendreApercu()
verifier(await apercu() === f12345, '?graine=12345 : toujours la même fiche')

console.log('Exemple à corpus (QCM)')
await ouvrir('/dev/exemple-corpus')
await cliquer('nbQ', '5')
await page.locator('.actions .btn-primary').click()
await page.waitForSelector('.choix-btn')
for (let i = 1; i <= 5; i++) {
  await page.waitForFunction(n => document.querySelector('.score-bar span')?.textContent?.includes(String(n)), i)
  await page.locator('.choix-btn').first().click()
  await page.waitForSelector('.choix-btn.ok')
  verifier(await page.locator('.choix-btn.ok').count() === 1, `question ${i} : la bonne proposition est colorée`)
  if (await suivant().count()) await suivant().click()
  else await page.clock.runFor(2000)
}
await page.waitForSelector('.resultats-jeu')
verifier(/\/\s*5/.test(await page.locator('.result-score').textContent()), 'résultats sur 5 questions')

console.log('Calcul mental (exercice reporté) : jeu, minuteur et fiche')
await ouvrir('/maths/calcul-mental')
await cliquer('niveau', 'cp')
await cliquer('nbQ', '5')
await cliquer('temps', '0')
verifier(JSON.stringify(await actifs('ops')) === '["+","−"]', 'CP : « + » et « − » cochés par défaut')
verifier(await page.locator('[data-reglage="tables"]').count() === 0, 'CP : pas de réglage « tables » (l\'exercice n\'en propose qu\'au CE1 et au CE2)')
await page.locator('.actions .btn-primary').click()
await page.waitForSelector('.score-bar')
// la réponse d'un calcul « 7 + 5 = ? » ou « 12 − 4 = ? » lue à l'écran (opérations par défaut)
const calcul = () => page.locator('.exercise-question').textContent().then(t => {
  const [, a, op, b] = /(\d+) ([+−]) (\d+) = \?/.exec(t ?? '') ?? []
  return op === '+' ? +a + +b : +a - +b
})
await saisir((await calcul()) + 1)
await page.waitForSelector('.feedback.erreur')
verifier((await page.locator('.feedback.erreur').textContent()).includes('❌'), 'mauvaise réponse : la bonne est donnée')
await page.clock.runFor(1500)   // après une erreur, la question suivante arrive seule
await page.waitForFunction(() => document.querySelector('.score-bar span')?.textContent?.includes('2'))
await saisir(await calcul())
await page.waitForSelector('.feedback.ok')
await page.clock.runFor(2000)
await page.waitForFunction(() => document.querySelector('.score-bar span')?.textContent?.includes('3'))
verifier(true, 'une bonne réponse passe seule à la question suivante')
await page.locator('.btn-quitter').click()
await page.waitForSelector('.cadre-exercice')
console.log('Calcul mental : temps écoulé')
await cliquer('temps', '10')
await page.locator('.actions .btn-primary').click()
await page.waitForSelector('.chronometre')
await page.clock.runFor(11000)
await page.waitForFunction(() => /Temps écoulé|Echu eo an amzer/.test(document.querySelector('.feedback')?.textContent ?? ''))
verifier(true, 'temps écoulé : la question est comptée fausse, avec la bonne réponse')
await page.clock.runFor(1500)
await page.waitForFunction(() => document.querySelector('.score-bar span')?.textContent?.includes('2'))
verifier(true, 'après un temps écoulé, la question suivante arrive seule')
await page.locator('.btn-quitter').click()
await page.waitForSelector('.cadre-exercice')
console.log('Calcul mental : fiche reproductible')
await page.goto('about:blank')
await page.goto(appDev('/maths/calcul-mental?mode=imprimer&graine=12345'))
await attendreApercu()
const fiche = await apercu()
verifier(/class="calc"/.test(fiche) && /<section class="corrige/.test(fiche), 'la fiche montre des calculs et un corrigé')
await page.goto('about:blank')
await page.goto(appDev('/maths/calcul-mental?mode=imprimer&graine=12345'))
await attendreApercu()
verifier(await apercu() === fiche, '?graine=12345 : toujours la même fiche')

console.log("Lire l'heure (exercice reporté) : le CP ne lit pas les minutes, jeu, placer les aiguilles, fiche")
await ouvrir('/maths/heure')
await cliquer('niveau', 'cp')
await cliquer('nbQ', '5')
verifier(await page.locator('.config-section-title', { hasText: /Aide|Skoazell/ }).count() === 0, 'CP : pas de réglage « minutes autour du cadran »')
await cliquer('saisie', 'choix')
await page.locator('.actions .btn-primary').click()
await page.waitForSelector('.score-bar')
const propositions = await page.locator('.choix-btn').allTextContents()
verifier(propositions.length === 4 && propositions.every(p => !/\d+ h \d|munut|minute/.test(p)), 'CP : quatre propositions, des heures pile seulement')
verifier(!(await page.locator('.horloge').innerHTML()).includes('font-size="11"'), 'CP : aucune minute écrite autour du cadran')
await page.locator('.choix-btn').first().click()
await page.waitForSelector('.feedback.ok, .feedback.erreur')
verifier(true, 'une réponse donne un retour')
await page.locator('.btn-quitter').click()
await page.waitForSelector('.cadre-exercice')
await cliquer('exercices', 'placer')
await cliquer('exercices', 'lire')
await page.locator('.actions .btn-primary').click()
await page.waitForSelector('.horloge.deplacable')
verifier(await page.locator('.reglage').count() === 1, 'CP, placer les aiguilles : seulement la petite aiguille se règle (la grande reste sur le 12)')
await page.locator('.exercise-box .btn-primary').click()
await page.waitForSelector('.feedback.ok, .feedback.erreur')
verifier(true, 'placer les aiguilles : valider donne un retour')
await page.locator('.btn-quitter').click()
await page.waitForSelector('.cadre-exercice')
await cliquer('niveau', 'ce1')
verifier(await page.locator('.config-section-title', { hasText: /Aide|Skoazell/ }).count() === 1, 'CE1 : les minutes autour du cadran sont proposées')
console.log("Lire l'heure : fiche reproductible")
await cliquer('niveau', 'cp')
await page.goto('about:blank')
await page.goto(appDev('/maths/heure?mode=imprimer&graine=12345'))
await attendreApercu()
const ficheHeure = await apercu()
verifier(/<svg/.test(ficheHeure) && /<section class="corrige/.test(ficheHeure) && !ficheHeure.includes('font-size="11"'), 'la fiche CP montre des horloges, un corrigé et pas de minutes autour du cadran')
await page.goto('about:blank')
await page.goto(appDev('/maths/heure?mode=imprimer&graine=12345'))
await attendreApercu()
verifier(await apercu() === ficheHeure, "?graine=12345 : toujours la même fiche d'heure")

console.log('La monnaie (exercice reporté) : compter, faire une somme, fiche')
await ouvrir('/maths/monnaie')
await cliquer('niveau', 'cp')
await cliquer('nbQ', '5')
verifier(await page.locator('[data-reglage="centimes"] [data-valeur="true"]').count() === 0, 'CP : pas de centimes (euros entiers seulement)')
await cliquer('exercices', 'composer')   // reste « compter »
await page.locator('.actions .btn-primary').click()
await page.waitForSelector('.score-bar')
// la somme des pièces et des billets montrés, lue dans leur nom (« billet de 5 € », « pièce de 2 € » : lecteurs d'écran)
const sommeAffichee = () => page.locator('.tas [role="img"]').evaluateAll(l => l.reduce((t, e) => t + Number(/(\d+) €/.exec(e.getAttribute('aria-label') ?? '')?.[1] ?? 0), 0))
await saisir((await sommeAffichee()) + 1)
await page.waitForSelector('.feedback.erreur')
verifier((await page.locator('.feedback.erreur').textContent()).includes('❌'), 'compter : une mauvaise réponse donne la correction')
await suivant().click()
await page.waitForFunction(() => document.querySelector('.score-bar span')?.textContent?.includes('2'))
await saisir(await sommeAffichee())
await page.waitForSelector('.feedback.ok')
await page.clock.runFor(2000)
await page.waitForFunction(() => document.querySelector('.score-bar span')?.textContent?.includes('3'))
verifier(true, 'compter : une bonne réponse passe seule à la question suivante')
await page.locator('.btn-quitter').click()
await page.waitForSelector('.cadre-exercice')
await cliquer('exercices', 'composer')
await cliquer('exercices', 'compter')   // reste « faire une somme »
await page.locator('.actions .btn-primary').click()
await page.waitForSelector('.plateau')
// la cible (« faire 17 € ») : on pose les pièces et les billets de la palette, du plus grand au plus petit
const faireLaSomme = async () => {
  let reste = Number(/(\d+)/.exec(await page.locator('.consigne .somme').textContent() ?? '')?.[1])
  const valeurs = await page.locator('.palette .btn-argent').evaluateAll(l => l.map((e, i) => [i, Number(/(\d+) €/.exec(e.getAttribute('title') ?? '')?.[1])]).sort((a, b) => b[1] - a[1]))
  for (const [i, v] of valeurs) while (reste >= v) { await page.locator('.palette .btn-argent').nth(i).click(); reste -= v }
}
await faireLaSomme()
verifier(await page.locator('.plateau .btn-argent').count() > 0 && await page.locator('.total-aide').count() === 1, 'faire une somme : les pièces posées sont sur le plateau, avec le total')
await page.locator('.exercise-box .btn-primary').click()
await page.waitForSelector('.feedback.ok')
verifier(true, 'faire une somme : la bonne somme est juste')
await page.locator('.btn-quitter').click()
await page.waitForSelector('.cadre-exercice')
console.log('La monnaie : fiche reproductible')
await page.goto('about:blank')
await page.goto(appDev('/maths/monnaie?mode=imprimer&graine=12345'))
await attendreApercu()
const ficheMonnaie = await apercu()
verifier(/<svg/.test(ficheMonnaie) && /aria-label="(billet|pièce) de/.test(ficheMonnaie) && /<section class="corrige/.test(ficheMonnaie), 'la fiche montre des pièces et des billets nommés, et un corrigé')
await page.goto('about:blank')
await page.goto(appDev('/maths/monnaie?mode=imprimer&graine=12345'))
await attendreApercu()
verifier(await apercu() === ficheMonnaie, '?graine=12345 : toujours la même fiche de monnaie')

verifier(!erreurs.length, `aucune erreur JavaScript${erreurs.length ? ` (${erreurs[0]})` : ''}`)
await nav.close()
process.exit(nbEchecs() ? 1 : 0)
