// Textes de l'interface — page d'accueil (français) : trois dispositions (enfant, parent, enseignant).
export default {
  titre: 'Des exercices et des fiches à imprimer pour l’école',
  sousTitre: 'De la petite section au CM2, gratuit, sans compte.',
  titreEnfant: 'Bonjour !',
  maClasse: 'Ma classe',
  mesClasses: 'Mes classes',
  verrou: 'La classe est verrouillée (cadenas en haut) : un adulte peut l’ouvrir.',
  tuile: {
    maths: 'Maths',
    francais: 'Français',
    monde: 'Le Monde',
    programme: 'Programme',
    fiches: 'Fiches toutes prêtes',
  },
  // n = nombre de ressources (la forme), classes = « CE1 + CE2 »
  compte: { one: '{n} ressource · {classes}', other: '{n} ressources · {classes}' },
  aucune: 'Les ressources arrivent · {classes}',
  mondeDesc: 'Le quiz, et ce qui arrive : sciences, histoire, géographie',
  programmeDesc: 'Ce qu’on apprend : {classes}',
  programmeDescEnseignant: 'Classe × domaine → compétences → ressources',
  fichesDesc: 'PDF à télécharger et imprimer, sans rien régler',
  reprendre: 'Reprendre',
  anciennete: { aujourdhui: 'aujourd’hui', hier: 'hier', jours: { one: 'il y a {n} jour', other: 'il y a {n} jours' } },
  profil: {
    phrase: 'Vous êtes plutôt :',
    facultatif: '(facultatif, ne change que la disposition)',
    enfant: 'enfant',
    parent: 'parent',
    enseignant: 'enseignant',
  },
  copier: 'Copier le lien pour les familles',
  copierAide: 'Les familles arrivent sur le site déjà réglé sur {classes}.',
  copie: 'Lien copié : les familles arriveront sur {classes}.',
  copieEchec: 'Copie impossible. Voici le lien à envoyer :',
} as const
