// Textes de l'interface — cadre d'un exercice ou d'une affiche (CadreExercice, OptionsFiche, ChoixPolice, AjoutPolice du noyau), français.
export default {
  jouer: '🎯 Faire l’exercice',
  imprimer: '🖨️ Imprimer une fiche',
  nouvelle: '🎲 Nouvelle fiche',
  surLaFiche: 'Sur la fiche',
  entete: 'Prénom et date',
  corrige_non: 'Sans corrigé',
  corrige_page: 'Corrigé sur une autre page',
  corrige_dessous: 'Corrigé en bas, à l’envers',
  police: 'Police',
  exempleAttache: 'belle école',
  exempleScript: 'a b g école',
  retirer: 'Retirer cette police',
  aideTitre: '➕ Ajouter une police…',
  aideTexte: 'Ces polices scolaires sont gratuites pour la classe et la maison, mais leur licence ne permet pas de les livrer avec le site. Deux solutions : les <strong>installer</strong> sur l’ordinateur (elles apparaîtront dans la liste après rechargement de la page), ou <strong>ajouter le fichier</strong> ici (il reste mémorisé dans ce navigateur).',
  modes: 'Mode de l’exercice',
  installee: 'installée',
  nonInstallee: 'non installée',
  // sélecteur de police par groupes (ChoixPolice) et ajout d'une police (AjoutPolice)
  groupeNotres: 'Nos polices',
  groupeInstallees: 'Installées sur cet ordinateur',
  groupeAjoutees: 'Ajoutées depuis un fichier',
  aideLiens: 'À obtenir (pas encore installées sur cet ordinateur) :',
  ajouterFichier: '📂 Ajouter un fichier de police',
  toutesPolices: 'Afficher toutes les polices de cet ordinateur',
  toutesTrouvees: 'Polices de cet ordinateur ajoutées à la liste : {n}.',
  toutesRefusees: 'L’accès aux polices de l’ordinateur n’a pas été accordé.',
  nomPolice: 'Nom d’une police installée',
  chercherPolice: 'Chercher',
  nomTrouvee: '« {nom} » est installée : elle est ajoutée à la liste.',
  nomIntrouvable: '« {nom} » n’a pas été trouvée sur cet ordinateur : vérifiez l’orthographe exacte du nom.',
  noteSysteme: 'Cette police est celle de l’ordinateur : elle n’est pas incluse dans la fiche. Elle ne s’imprime bien que depuis cet ordinateur (pas dans un PDF téléchargé, ni depuis un autre appareil).',
  // polices incluses et notes sur les polices à obtenir ailleurs (ChoixPolice)
  policeAttache: 'Playwrite FR Trad — cursive scolaire française',
  policeAndika: 'Andika — conçue pour apprendre à lire (a et g simples)',
  policeLuciole: 'Luciole — très lisible, conçue pour les enfants malvoyants',
  policeOpenDyslexic: 'OpenDyslexic — pour les lecteurs dyslexiques',
  noteBelleAllure: 'cursive très utilisée en classe, plusieurs variantes (GS, CP, CE…)',
  noteEcolier: 'cursive classique, version « court » pour petites boucles',
  noteCursif: 'et d’autres polices scolaires (catégorie Script › Scolaire)',
  // erreurs de l'ajout d'une police depuis un fichier (src/utils/impression.js)
  erreurPoliceTropGrosse: 'Fichier trop gros (3 Mo maximum)',
  erreurPoliceNonMemorisee: 'Police chargée pour cette session, mais impossible de la mémoriser (stockage du navigateur plein)',
} as const
