// Textes de l'interface — cadre d'un exercice ou d'une affiche (CadreExercice, OptionsFiche, ChoixPolice du noyau), français.
export default {
  jouer: '🎯 Faire l’exercice',
  imprimer: '🖨️ Imprimer une fiche',
  nouvelle: '🎲 Nouvelle fiche',
  surLaFiche: 'Sur la fiche',
  entete: 'Prénom et date',
  corrige_non: 'Sans corrigé',
  corrige_page: 'Corrigé sur une autre page',
  corrige_dessous: 'Corrigé en bas, à l’envers',
  attache: 'Attaché',
  script: 'Script',
  police: 'Police',
  exempleAttache: 'belle école',
  exempleScript: 'a b g école',
  retirer: 'Retirer cette police',
  aideTitre: '➕ Utiliser Belle Allure, Écolier ou une autre police…',
  aideTexte: 'Ces polices scolaires sont gratuites pour la classe et la maison, mais leur licence ne permet pas de les livrer avec le site. Deux solutions : les <strong>installer</strong> sur l’ordinateur (elles apparaîtront dans la liste après rechargement de la page), ou <strong>ajouter le fichier</strong> ici (il reste mémorisé dans ce navigateur).',
  ajouterAttache: '📂 Ajouter une police attachée',
  ajouterScript: '📂 Ajouter une police script',
  astuce: 'Astuce Belle Allure : choisis le fichier sans lignes (pas « Ductus » ni « Lignes ») ; la taille est ajustée automatiquement au lignage Seyès.',
  modes: 'Mode de l’exercice',
  installee: 'installée',
  ajoutee: 'ajoutée',
  // polices incluses et notes sur les polices à obtenir ailleurs (ChoixPolice)
  policeAttache: 'Playwrite FR Trad — cursive scolaire française',
  policeAndika: 'Andika — conçue pour apprendre à lire (a et g simples)',
  policeLuciole: 'Luciole — très lisible, conçue pour les enfants malvoyants',
  policeOpenDyslexic: 'OpenDyslexic — pour les lecteurs dyslexiques',
  noteBelleAllure: 'cursive très utilisée en classe, plusieurs variantes (GS, CP, CE…)',
  noteEcolier: 'cursive classique, version « court » pour petites boucles',
  noteCursif: 'et d’autres polices scolaires (catégorie Script › Scolaire)',
  // erreurs de l'ajout d'une police depuis un fichier (src/utils/impression.js)
  erreurPoliceTropGrosse: 'Fichier trop gros (3 Mo maximum)',
  erreurPoliceNonMemorisee: 'Police chargée pour cette session, mais impossible de la mémoriser (stockage du navigateur plein)',
} as const
