// Textes de l'interface — dictée (français) : la page et le jeu. Source des clés : br/textes/dictee.ts doit avoir exactement les mêmes.
// La fiche est dans le catalogue de contenu de l'exercice : src/exercices/dictee/textes.ts.
export default {
  description: 'Écoute et écris les mots — synthèse vocale',
  titre: 'Dictée',
  categories: 'Catégories — {n}',
  mode: 'Mode',
  motsSeuls: 'Mots seuls',
  motsSeulsDesc: "L'élève entend le mot et le tape",
  phrases: 'Phrases',
  phrasesDesc: "Un mot dans une phrase, l'élève tape la phrase",
  cleApi: 'Clé API Mistral',
  cleApiOpt: '(optionnel — pour générer des phrases variées)',
  cleOk: '✓ Clé configurée',
  cleAucune: 'Aucune clé — phrases prédéfinies',
  nbMots: 'Nombre de mots',
  tous: 'Tous',
  vitesse: 'Vitesse de la voix',
  generation: 'Génération…',
  afficherIndice: '👁️ Afficher la phrase à trous (indice)',
  masquerIndice: "Masquer l'indice",
  arreter: 'Arrêter',
  ecouterPhrase: 'Écouter la phrase',
  ecouterMot: 'Écouter le mot',
  consigne: 'Écoute bien, puis tape ce que tu entends :',
  reecouter: '🔁 Réécouter',
  accents: 'Attention aux accents : {r}',
  feedbackErr: '❌ La bonne réponse était : « {r} »',
  pagesFiche: 'Pages de la fiche',
  pageListe: 'Mots à apprendre',
  pageDictee: 'Dictée à faire avec un adulte',
  cleSaisie: 'Ta clé Mistral',
  cleEnregistrer: 'Enregistrer',
  cleEffacer: 'Effacer la clé',
  cleConfidentialite: 'La clé reste sur cet appareil. Elle n’est envoyée qu’à Mistral (api.mistral.ai), seulement pour écrire des phrases ; sans clé, rien ne sort du navigateur.',
  passer: 'Passer',
  passe: '(passé)',
  cat: {
    mots_outils: 'Mots outils',
    pronoms: 'Pronoms',
    jours: 'Jours',
    nombres: 'Nombres',
    lieux: 'Lieux',
    transports: 'Transports',
    animaux: 'Animaux',
    fruits: 'Fruits',
    famille: 'Famille',
    verbes: 'Verbes',
    determinants: 'Déterminants',
    corps_humain: 'Corps humain',
    maison: 'Maison',
    ecole: 'École',
    verbes_courants: 'Verbes courants',
    adjectifs: 'Adjectifs',
    saisons: 'Saisons',
    aliments: 'Aliments',
    mots_invariables: 'Mots invariables',
    mots_en_tion: 'Mots en -tion',
    mots_en_eur: 'Mots en -eur',
    nature_et_environnement: 'Nature et environnement',
    vocabulaire_scientifique: 'Vocabulaire scientifique',
    adverbes: 'Adverbes',
    vocabulaire_civique: 'Vocabulaire civique',
    vocabulaire_geographique: 'Vocabulaire géographique',
    mots_difficiles_courants: 'Mots difficiles courants',
    connecteurs_logiques: 'Connecteurs logiques',
    vocabulaire_litteraire: 'Vocabulaire littéraire',
    mots_latins_grecs_courants: 'Mots latins/grecs courants',
  },
} as const
