// Textes de l'interface — écriture (français) : la page de réglages de la fiche. Source des clés : br/textes/ecriture.ts doit avoir
// exactement les mêmes. Ce que la fiche écrit (titre, Prénom, Date) est dans le catalogue de contenu : src/exercices/ecriture/textes.ts.
export default {
  titre: "Fiches d'écriture",
  description: 'Lignes Seyès : le modèle, des lettres à repasser, des lignes pour écrire seul',
  intro: 'Lignage Seyès (comme le cahier de classe), modèle en noir au début de chaque ligne, lettres grises à repasser puis lignes pour copier seul.',
  ecritures: 'Écritures (plusieurs choix possibles)',
  style: {
    'script-maj': 'Script majuscule',
    'script-min': 'Script minuscule',
    'attache-maj': 'Attaché majuscule',
    'attache-min': 'Attaché minuscule',
  },
  contenu: 'Contenu',
  contenus: { lettres: '🔤 Lettres et chiffres', mots: '📝 Mots', texte: '📄 Phrases' },
  lettres: 'Lettres',
  familles: 'Familles de lettres',
  famille: {
    alphabet: 'Alphabet',
    voyelles: 'Voyelles',
    rondes: 'Rondes (c o a d g q)',
    boucles: 'Boucles (e l b h k f)',
    coupes: 'Coupes (i u t)',
    ponts: 'Ponts (m n v w x y)',
    jambages: 'Jambages (j p g q y f z)',
    particulieres: 'Particulières (r s z x)',
    accents: 'Accents et œ',
    chiffres: 'Chiffres',
  },
  alphabetRegional: 'Alphabet {nom}',
  lier: 'En attaché minuscule, lier les lettres par trois (aaa)',
  mots: 'Mots (un par ligne : prénom, mots de la semaine…)',
  listes: 'Listes toutes prêtes',
  liste: { jours: 'Jours de la semaine', mois: "Mois de l'année", nombres: 'Nombres 1 → 10', couleurs: 'Couleurs', famille: 'Famille' },
  // une liste française proposée sur une interface dans une autre langue : en français
  listeEnFrancais: '{nom}',
  texte: 'Phrases ou petit texte (un paragraphe par ligne)',
  titreFiche: 'Titre de la fiche',
  titreAuto: 'Automatique : « Écriture — » et les écritures choisies',
  taille: 'Taille du lignage',
  interligne: { i2: '2 mm (CE2 et +)', i25: '2,5 mm (CE1)', i3: '3 mm (CP)', i4: '4 mm (débutant)' },
  espacement: 'Espacement',
  uneSurDeux: 'Une ligne sur deux',
  chaqueLigne: 'Chaque ligne',
  repasser: 'Lignes à repasser (gris)',
  copie: 'Lignes à copier seul',
  couleurLignes: 'Couleur des lignes',
  couleur: 'Couleur',
  gris: 'Gris (imprimante N&B)',
  polices: 'Polices',
  policeScript: 'Script',
  policeAttache: 'Attaché',
} as const
