// Textes de l'interface — fiches toutes prêtes (français) : la liste d'une matière (/maths/fiches…) et l'index /telechargements.
// Source des clés : br/textes/fichesPretes.ts doit avoir exactement les mêmes.
export default {
  titre: 'Fiches toutes prêtes — {matiere}',
  titreIndex: 'Toutes les fiches à imprimer',
  intro: 'PDF à télécharger et imprimer, sans rien régler. Pour modifier une fiche, ouvrez-la puis « Personnaliser ».',
  introIndex: 'Toutes les fiches toutes prêtes du site, matière par matière, de A à Z.',
  fil: 'Fil d’Ariane',
  accueil: 'Accueil',
  fichesPretes: 'Fiches toutes prêtes',
  matieres: { maths: 'Maths', francais: 'Français', monde: 'Le Monde', regionale: 'Langue régionale' },
  // filtres
  filtres: 'Filtrer les fiches',
  rechercher: 'Rechercher',
  exemple: 'ex. heure, tables, symétrie',
  classe: 'Classe',
  toutesClasses: '🌐 Toutes les classes',
  usage: 'Usage',
  tous: '🌐 Tous',
  apprendre: '🖼️ À afficher',
  sentrainer: '✏️ Pour s’entraîner',
  domaine: 'Domaine',
  tousDomaines: '🌐 Tous les domaines',
  langue: 'Langue',
  toutesLangues: '🌐 Toutes',
  bilingue: 'Bilingue',
  compteurClasses: { one: '{n} fiche pour {classes}', other: '{n} fiches pour {classes}' },
  compteurToutes: { one: '{n} fiche, toutes classes', other: '{n} fiches, toutes classes' },
  // cartes et liste
  liste: 'Fiches',
  pdfPages: { one: 'PDF · {n} page', other: 'PDF · {n} pages' },
  pages: { one: '{n} page', other: '{n} pages' },
  badgeExemple: 'exemple',
  colonnes: { titre: 'Titre', domaine: 'Domaine', classes: 'Classes', pages: 'Pages', actions: 'Actions' },
  ouvrir: 'Ouvrir',
  ouvrirTitre: 'Ouvrir : {titre}',
  // états
  chargement: 'Chargement des fiches…',
  vide: 'Les fiches toutes prêtes arrivent : il n’y en a pas encore sur ce site. Les exercices à imprimer, eux, se personnalisent déjà depuis chaque matière.',
  videMatiere: 'Pas encore de fiche toute prête dans cette matière.',
  absent: 'La liste des fiches est introuvable pour le moment.',
  absentDev: 'En développement, produisez-la avec « npm run fiches:dev », puis rechargez la page.',
  erreur: 'Les fiches n’ont pas pu être lues : {message}',
  reessayer: 'Réessayer',
  aucune: 'Aucune fiche avec ces filtres.',
  effacer: 'Tout réinitialiser',
  // liens
  personnaliserTitre: 'Besoin d’une fiche sur mesure ?',
  personnaliserTexte: 'Choisissez les nombres, le nombre de lignes, ajoutez un corrigé : les exercices se personnalisent depuis la page de la matière.',
  personnaliser: 'Personnaliser vos fiches →',
  toutesLesFiches: 'Toutes les fiches, de A à Z',
  lienPied: 'Fiches toutes prêtes',
} as const
