// Textes de l'interface — formulaire d'une affiche (FormulaireAffiche du noyau), français.
export default {
  version: 'Version',
  copierLien: 'Copier le lien',
  lienCopie: 'Lien copié ✓',
  versionAide: 'Choisissez une fiche toute prête : elle règle tout le reste, que vous pouvez ensuite modifier.',
  personnaliser: 'Personnaliser',
  personnaliserAide: 'Ajustez cette version : contenu, langues, feuille, polices.',
  langue: 'Langue de l’affiche',
  langues: 'Langues affichées',
  titre: 'Titre de l’affiche',
  titreVide: 'Facultatif : sinon le titre habituel',
  hasard: 'Contenu tiré au hasard',
  nouvelle: 'Nouvelle',
  feuille: 'La feuille',
  policeTexte: 'Police du texte',
  format: 'Format',
  orientation: 'Orientation',
  paysage: 'Paysage',
  portrait: 'Portrait',
  prereglages: 'Préréglages',
  polices: 'Polices',
} as const
