// Textes de l'interface — grammaire (français) : la page et le jeu, et les textes calculés des questions (consignes, explications,
// libellés des choix) que le générateur demande avec leur clé seule (`grammaire.<clé>`). La fiche lit les mêmes textes en français
// (src/moteurs/grammaire/textes.ts). Source des clés : br/textes/grammaire.ts doit avoir exactement les mêmes.
export default {
  astuce: 'Tu peux choisir plusieurs exercices : ils seront mélangés.',
  ecouterPhrase: 'Écouter la phrase',
  cliqueEtiquettes: 'Clique sur les étiquettes dans l\'ordre…',
  effacerOrdre: '↺ Effacer',
  ecrisReponse: 'Écris ta réponse…',
  validerCourt: 'Valider',
  suivantFleche: 'Suivant →',
  correction: 'Correction',
  bonnePhrase: 'La bonne phrase est : « {r} »',
  bonneReponseEst: 'La bonne réponse est « {r} »',
  accents: 'Attention aux accents : {r}',
  pasToutAFait: 'Pas tout à fait…',
  // Groupes et types d'exercices (réglages)
  type_ordre: 'Mots dans l\'ordre',
  type_phrase: 'Phrase ou pas ?',
  type_majuscule: 'Majuscule et point',
  type_ponctuation: 'Le bon signe . ? !',
  type_typePhrase: 'Déclarative, interrogative, impérative',
  type_complexe: 'Phrase simple / complexe',
  type_negation: 'Mettre à la forme négative',
  type_negReconnaitre: 'Affirmative ou négative ?',
  type_verbe: 'Trouver le verbe',
  type_nom: 'Trouver les noms',
  type_det: 'Trouver les déterminants',
  type_adj: 'Trouver les adjectifs',
  type_nature: 'Nature d\'un mot',
  type_gnNoyau: 'Nom principal du GN',
  type_sujet: 'Trouver le sujet',
  type_pronom: 'Il, elle, ils, elles',
  type_pronomPersonne: 'Je, tu, nous, vous…',
  type_cplt: 'Trouver le complément de phrase',
  type_cpltQ: 'Où ? Quand ?',
  type_cpltNature: 'Complément du verbe ou de phrase ?',
  type_genre: 'Masculin / féminin',
  type_nombre: 'Singulier / pluriel',
  type_pluriel: 'Mettre au pluriel',
  type_accordGN: 'Accorder l\'adjectif',
  type_accordSV: 'Il chante / ils chantent',
  // Choix de réponse « métalangage » (les choix en français étudié restent tels quels)
  choix_ouiPhrase: 'Oui, c\'est une phrase',
  choix_nonPhrase: 'Non, ce n\'est pas une phrase',
  choix_phraseSimple: 'phrase simple',
  choix_phraseComplexe: 'phrase complexe',
  choix_affirmative: 'affirmative',
  choix_negative: 'négative',
  choix_complementVerbe: 'complément du verbe',
  choix_complementPhrase: 'complément de phrase',
  choix_ou: 'Où ?',
  choix_quand: 'Quand ?',
  choix_singulier: 'singulier',
  choix_pluriel: 'pluriel',
  choix_masculin: 'masculin',
  choix_feminin: 'féminin',
  choix_nom: 'nom',
  choix_verbe: 'verbe',
  choix_determinant: 'déterminant',
  choix_adjectif: 'adjectif',
  choix_pronom: 'pronom',
  choix_point: '. (point)',
  choix_interrogation: '? (point d\'interrogation)',
  choix_exclamation: '! (point d\'exclamation)',
  choix_declarative: 'déclarative',
  choix_interrogative: 'interrogative',
  choix_imperative: 'impérative',
  // Genre et nombre dans les explications
  gn_ms: 'masculin singulier',
  gn_fs: 'féminin singulier',
  gn_mp: 'masculin pluriel',
  gn_fp: 'féminin pluriel',
  nombre_s: 'au singulier',
  nombre_p: 'au pluriel',
  // Types de phrases (selon le signe de fin)
  typePhrase_point: 'phrase déclarative',
  typePhrase_interrogation: 'phrase interrogative',
  typePhrase_exclamation: 'phrase à la forme exclamative',
  // Consignes des questions (à l'écran)
  consigne_ordre: 'Remets les mots dans l\'ordre pour faire une phrase.',
  consigne_phrase: 'Est-ce une phrase ?',
  consigne_majuscule: 'Quelle phrase est bien écrite ?',
  consigne_ponctuation: 'Quel signe faut-il mettre à la fin de la phrase ?',
  consigne_typePhrase: 'Quel est le type de cette phrase ?',
  consigne_complexe: 'Cette phrase est-elle simple ou complexe ?',
  consigne_negation: 'Quelle est la phrase à la forme négative ?',
  consigne_negReconnaitre: 'Cette phrase est-elle affirmative ou négative ?',
  consigne_verbe: 'Clique sur le verbe.',
  consigne_nom: 'Clique sur tous les noms.',
  consigne_det: 'Clique sur tous les déterminants.',
  consigne_adj: 'Clique sur tous les adjectifs.',
  consigne_nature: 'Quelle est la nature du mot en gras ?',
  consigne_gnNoyau: 'Clique sur le nom principal du groupe nominal.',
  consigne_sujet: 'Clique sur tous les mots du groupe sujet.',
  consigne_pronom: 'Par quel pronom peut-on remplacer le sujet souligné ?',
  consigne_pronomPersonne: 'Quel pronom personnel sujet faut-il ?',
  consigne_cplt: 'Clique sur tous les mots du complément de phrase.',
  consigne_cpltQ: 'Le complément de phrase souligné répond à quelle question ?',
  consigne_cpltNature: 'Le groupe souligné est-il un complément du verbe ou un complément de phrase ?',
  consigne_genre: 'Un ou une ?',
  consigne_nombre: 'Singulier ou pluriel ?',
  consigne_pluriel: 'Écris ce groupe de mots au pluriel.',
  consigne_accordGN: 'Choisis le bon accord de l\'adjectif.',
  consigne_accordSV: 'Choisis la bonne forme du verbe (au présent).',
  consigne_ce2_verbe: 'Clique sur tous les verbes conjugués.',
  consigne_ce2_negReconnaitre: 'Cette phrase est-elle affirmative ? Sinon, quelle négation contient-elle ?',
  // Règles du pluriel (explication)
  regle_al: 'Les noms en -al font leur pluriel en -aux.',
  regle_eu: 'Les noms en -eu prennent un x au pluriel.',
  regle_eau: 'Les noms en -eau prennent un x au pluriel.',
  regle_ou: 'Sept noms en -ou prennent un x au pluriel : bijou, caillou, chou, genou, hibou, joujou, pou.',
  regle_ou2: 'Les noms en -ou prennent un s au pluriel, sauf bijou, caillou, chou, genou, hibou, joujou, pou.',
  regle_s: 'Un mot qui finit déjà par -s ne change pas au pluriel.',
  regle_x: 'Un mot qui finit déjà par -x ne change pas au pluriel.',
  regle_z: 'Un mot qui finit déjà par -z ne change pas au pluriel.',
  regle_defaut: 'Au pluriel, le déterminant change (le, la → les ; un, une → des…) et on ajoute un -s à la fin des noms et des adjectifs.',
  // Consignes de la fiche imprimée
  fiche_ordre: 'Remets les mots dans l\'ordre et écris la phrase.',
  fiche_phrase: 'Coche la bonne case : est-ce une phrase ?',
  fiche_majuscule: 'Recopie la phrase avec une majuscule et un point.',
  fiche_ponctuation: 'Ajoute le bon signe à la fin : . ? ou !',
  fiche_typePhrase: 'Coche le type de la phrase : déclarative, interrogative ou impérative.',
  fiche_complexe: 'Souligne les verbes conjugués, puis coche : phrase simple ou complexe ?',
  fiche_negation: 'Écris la phrase à la forme négative.',
  fiche_negReconnaitre: 'Coche : la phrase est-elle affirmative ou négative ?',
  fiche_verbe: 'Souligne le verbe.',
  fiche_nom: 'Entoure tous les noms.',
  fiche_det: 'Entoure tous les déterminants.',
  fiche_adj: 'Entoure tous les adjectifs.',
  fiche_nature: 'Écris la nature du mot en gras : nom, verbe, déterminant, adjectif ou pronom.',
  fiche_gnNoyau: 'Souligne le nom principal du groupe nominal.',
  fiche_sujet: 'Entoure le groupe sujet.',
  fiche_pronom: 'Écris le pronom qui remplace le sujet souligné : il, elle, ils ou elles.',
  fiche_pronomPersonne: 'Écris le pronom qui remplace le groupe souligné, ou qui manque : je, tu, il, elle, nous, vous, ils ou elles.',
  fiche_cplt: 'Entoure le complément de phrase.',
  fiche_cpltQ: 'Le complément souligné indique-t-il où ou quand ? Coche.',
  fiche_cpltNature: 'Le groupe souligné est-il un complément du verbe (V) ou un complément de phrase (P) ?',
  fiche_genre: 'Écris un ou une.',
  fiche_nombre: 'Coche : singulier ou pluriel ?',
  fiche_pluriel: 'Écris au pluriel.',
  fiche_accordGN: 'Accorde l\'adjectif entre parenthèses.',
  fiche_accordSV: 'Écris le verbe au présent.',
  fiche_ce2_verbe: 'Souligne tous les verbes conjugués.',
  fiche_ce2_negReconnaitre: 'Écris A si la phrase est affirmative, sinon écris la négation (ne … pas, plus, jamais, rien).',
  fiche_cestPhrase: 'c\'est une phrase',
  fiche_pasPhrase: 'ce n\'est pas une phrase',
  // case « complément de phrase » (P) à côté de V (verbe)
  fiche_lettrePhrase: 'P',
  avec: 'avec',
  // Explications des corrections ({…} : mots de la phrase étudiée, en français)
  expl_phraseOk: 'Les mots sont dans l\'ordre et la phrase a du sens.',
  expl_phraseVerbe: 'Il manque un verbe : on ne sait pas ce qui se passe.',
  expl_phraseOrdre: 'Les mots ne sont pas dans le bon ordre : on ne comprend pas.',
  expl_majuscule: 'Une phrase commence par une majuscule et se termine par un point.',
  expl_ponctuation: 'C\'est une {type}.',
  expl_typePhrase_declarative: 'Elle dit quelque chose, elle donne une information : c\'est une phrase déclarative.',
  expl_typePhrase_interrogative: 'Elle pose une question, on attend une réponse : c\'est une phrase interrogative.',
  expl_typePhrase_imperative: 'Elle donne un ordre ou un conseil, sans dire qui fait l\'action : c\'est une phrase impérative. Elle finit par un point, ou un point d\'exclamation quand on insiste.',
  expl_complexe: 'Il y a {n} verbes conjugués ({verbes}) : c\'est une phrase complexe.',
  expl_simple: 'Il n\'y a qu\'un verbe conjugué ({verbes}) : c\'est une phrase simple.',
  expl_negation: 'On encadre le verbe avec « {ne} … {mot} »{elision}.',
  expl_negationElision: ' (n\' devant une voyelle)',
  expl_negative: 'Le verbe est encadré par « {ne} … {mot} » : la phrase est négative.',
  expl_affirmative: 'Il n\'y a pas de « ne … » autour du verbe : la phrase est affirmative.',
  expl_sujet: 'Le sujet est « {sujet} ». {cestQui}',
  expl_sujetInverse: ' Ici, le sujet est placé après le verbe.',
  expl_cplt: '« {groupe} » est un complément de phrase : il indique {question}. On peut le déplacer ou le supprimer.',
  expl_cpltOu: 'où',
  expl_cpltQuand: 'quand',
  expl_gnNoyau: 'Le nom principal est « {nom} » : les autres mots s\'accordent avec lui.',
  expl_verbes: 'Les verbes conjugués sont {verbes}.',
  expl_verbe: 'Le verbe est {verbes}.',
  lib_nom: 'Nom',
  lib_noms: 'Noms',
  lib_det: 'Déterminant',
  lib_dets: 'Déterminants',
  lib_adj: 'Adjectif',
  lib_adjs: 'Adjectifs',
  expl_cpltQ: '« {groupe} » indique {quoi}.',
  expl_cpltQLieu: 'le lieu (où ?)',
  expl_cpltQMoment: 'le moment (quand ?)',
  expl_cpltPhrase: 'On peut déplacer ou supprimer « {groupe} » : c\'est un complément de phrase.',
  expl_cpltVerbe: '« {groupe} » complète le verbe « {verbe} » : on ne peut pas le déplacer en début de phrase. C\'est un complément du verbe.',
  expl_nomPropre: ' (nom propre)',
  expl_conjugue: ' conjugué',
  expl_nature: '« {mot} » est un {nature}{precision}.',
  expl_pronom: '« {sujet} » est {gn} → {phrase}',
  expl_pronomPersonne_je: 'C\'est la personne qui parle qui fait l\'action : je.',
  expl_pronomPersonne_tu: 'C\'est la personne à qui l\'on parle qui fait l\'action : tu.',
  expl_pronomPersonne_il: '« {mots} » : un seul, au masculin → il.',
  expl_pronomPersonne_elle: '« {mots} » : une seule, au féminin → elle.',
  expl_pronomPersonne_nous: '« {mots} » : la personne qui parle, avec d\'autres → nous.',
  expl_pronomPersonne_vous: '« {mots} » : la personne à qui l\'on parle, avec d\'autres → vous.',
  expl_pronomPersonne_ils: '« {mots} » : plusieurs, dont au moins un garçon ou un nom masculin → ils.',
  expl_pronomPersonne_elles: '« {mots} » : plusieurs, toutes au féminin → elles.',
  expl_genre: 'On dit « {det} {nom} » : {nom} est {genre}.',
  expl_nombre: '« {det} » montre que c\'est {nombre}.',
  expl_accordGN: '« {nom} » est {gn} → {bonne}.',
  expl_accordSV: 'Le verbe s\'accorde avec son sujet « {sujet} », qui est {nombre} → {bonne}.',
} as const
