// Catalogue de l'interface en français : la SOURCE. Les autres langues ont exactement les mêmes clés (br/textes/index.ts
// et chaque section : `satisfies Traductions<typeof …>`, une clé manquante ou en trop ne compile pas).
// Une section par page ou composant ; les clés se lisent « section.cle » (t('nav.accueil')).
import nav from './nav.ts'
import accueil from './accueil.ts'
import reglages from './reglages.ts'
import regionale from './regionale.ts'
import matiere from './matiere.ts'
import monde from './monde.ts'
import ressource from './ressource.ts'
import apropos from './apropos.ts'
import shell from './shell.ts'
import avis from './avis.ts'
import nouveautes from './nouveautes.ts'
import cadre from './cadre.ts'
import formulaireAffiche from './formulaireAffiche.ts'
import communs from './communs.ts'
import domaines from './domaines.ts'
import routeur from './routeur.ts'
import statique from './statique.ts'
import recherche from './recherche.ts'
import programme from './programme.ts'
import competence from './competence.ts'
import fichesPretes from './fichesPretes.ts'
import feuille from './feuille.ts'
import exemple from './exemple.ts'
import exempleCorpus from './exempleCorpus.ts'
import dev from './dev.ts'
import calculMental from './calculMental.ts'
import heure from './heure.ts'
import numeration from './numeration.ts'
import monnaie from './monnaie.ts'
import compter from './compter.ts'
import comparer from './comparer.ts'
import ranger from './ranger.ts'
import tables from './tables.ts'
import calculPose from './calculPose.ts'
import mesures from './mesures.ts'
import fractions from './fractions.ts'
import longueurs from './longueurs.ts'
import suites from './suites.ts'
import problemes from './problemes.ts'
import formes from './formes.ts'
import geometrie from './geometrie.ts'
import motifs from './motifs.ts'
import { AVEC_DEV } from '../../../dev.ts'

// Textes des exemples et des pages /dev : absents d'un build de production (AVEC_DEV, src/dev.ts). Le type les garde : en production
// aucun code ne les lit (les exemples n'y sont pas).
const sectionsDev = (AVEC_DEV ? { exemple, exempleCorpus, dev } : {}) as { exemple: typeof exemple, exempleCorpus: typeof exempleCorpus, dev: typeof dev }

export default { nav, accueil, reglages, regionale, matiere, monde, ressource, apropos, shell, avis, nouveautes, cadre, formulaireAffiche, communs, domaines, routeur, recherche, programme, competence, fichesPretes, feuille, statique, calculMental, monnaie, heure, numeration, compter, comparer, ranger, tables, calculPose, suites, longueurs, fractions, problemes, mesures, formes, geometrie, motifs, ...sectionsDev } as const
