// Textes de l'interface — la monnaie (français) : la page et le jeu. Source des clés : br/textes/monnaie.ts doit avoir exactement les
// mêmes. Les énoncés et la fiche (objets à acheter, prénoms, consignes de la fiche, titres des fiches publiées) sont dans le
// catalogue de contenu de l'exercice : src/exercices/monnaie/textes.ts. Les mots communs (niveau, valider…) : section `communs`.
export default {
  titre: 'La monnaie',
  description: 'Compter et payer en euros',
  options: 'Options',
  eurosEntiers: 'Euros entiers',
  avecCentimes: 'Avec centimes',
  afficherTotal: 'Afficher le total pendant que je compose',
  aideFiche: 'La fiche reprend les exercices choisis.',
  combienArgent: "Combien d'argent y a-t-il ?",
  exemple: 'ex : 3,50 €',
  // noms des deux champs de la somme (lecteurs d'écran)
  euros: 'Euros',
  centimes: 'Centimes',
  tuPeuxEcrire: 'Tu peux écrire « 3,50 € » ou « 3 € 50 c ».',
  composer1: 'Clique sur les pièces et les billets pour faire',
  moins1: 'Paye',
  moins2: 'avec',
  moins3: 'le moins possible',
  moins4: 'de pièces et de billets',
  combienRendre: 'Combien doit-on te rendre ? Montre-le avec les pièces et les billets.',
  plateauVide: 'Ta monnaie apparaît ici',
  enlever: 'Enlever',
  ajouter: 'Ajouter',
  total: 'Total',
  toutEnlever: '🗑 Tout enlever',
  rappel: 'Rappel',
  quiPlus: "Qui a le plus d'argent ?",
  autantDeux: 'Autant tous les deux',
  ilYa: 'Il y a {s}.',
  astuceCompter: 'Astuce : commence par compter les billets, puis les grosses pièces.',
  noublie: "N'oublie pas",
  astuceConvertir: '1 € = 100 c : les euros vont avant la virgule, les centimes après (toujours 2 chiffres : 2 € 5 c = 2,05 €).',
  aSomme: ' a',
  astuceComparer: "Ce n'est pas le nombre de pièces qui compte, mais leur valeur !",
  avecMoins: 'Avec le moins de pièces et billets :',
  uneBonne: 'Une bonne réponse :',
  astuceRendre: "On compte de {prix} jusqu'à {paye} : il manque {cible}.",
  astuceMoins: "Astuce : prends d'abord le plus grand billet ou la plus grande pièce possible.",
  pasTout: 'Pas tout à fait… Regarde la correction.',
  ecrisSomme: 'Écris la somme comme « 3,50 € » ou « 3 € 50 c ».',
  auLieuDe: 'Tu as fait {t} au lieu de {c}.',
  tropDePieces: "C'est bien {t} 👍 mais on peut payer avec seulement {n} pièces et billets.",
  ilManque: 'Tu as fait {t} : il manque {m}.',
  deTrop: "Tu as fait {t} : c'est {m} de trop.",
  autantArgent: "Ils ont autant d'argent tous les deux : {s}.",
  lePlus: "C'est {nom} qui a le plus d'argent.",
  passer: 'Passer ⏭',
  passe: '(passé)',
  // types d'exercices (réglages)
  type_compter: '🔢 Compter une somme',
  type_composer: '🧩 Faire une somme',
  type_moins: '🪙 Le moins de pièces',
  type_rendre: '🛒 Rendre la monnaie',
  type_comparer: '👛 Comparer',
  type_convertir: '🔁 1 € = 100 c',
} as const
