// Textes de l'interface — enveloppe du site (français) : barre de navigation, menu du téléphone, pied de page.
// Source des clés : br/textes/shell.ts doit avoir exactement les mêmes.
export default {
  logoTitre: '{nom} — Accueil',
  barre: {
    menu: 'Menu principal',
    rubriques: 'Rubriques',
    menuTelephone: 'Menu',
    ouvrirMenu: 'Ouvrir le menu',
    fermerMenu: 'Fermer le menu',
    reglages: 'Réglages',
    rechercher: 'Rechercher',
    dev: 'Développement',
    accueil: 'Accueil',
    fichesPretes: 'Fiches toutes prêtes',
  },
  rubriques: {
    maths: 'Maths',
    francais: 'Français',
    monde: 'Le Monde',
    programme: 'Programme',
  },
  langue: {
    titre: 'Langue',
    etat: 'Langue : {mode}',
    fr: 'Français',
    frDesc: 'Interface, fiches et exercices en français',
    bilingue: 'Français + {langue}',
    bilingueDesc: 'Les deux langues : titres, fiches, exercices',
    regionale: '{langue} seul',
    regionaleDesc: 'Interface et matières en {langue}',
    retour: 'Retour en français',
    retourCourt: 'FR',
  },
  classe: {
    titre: 'Classe',
    etat: 'Classe : {classes}',
    maClasse: 'Ma classe',
    mesClasses: 'Mes classes (une ou plusieurs)',
    cycle1: 'Maternelle',
    cycle2: 'Cycle 2',
    cycle3: 'Cycle 3',
    toutes: 'Toutes les classes',
    noteUne: 'Une seule classe. Elle est mémorisée sur cet appareil.',
    notePlusieurs: 'Plusieurs classes : les listes montrent l’ensemble de ces classes.',
    verrouillee: 'Classe verrouillée : {classes}. Ouvrir le cadenas',
  },
  cadenas: {
    titre: 'Réservé aux grands',
    consigne: 'Pour changer de classe, un adulte maintient le bouton appuyé pendant 2 secondes.',
    bouton: 'Maintenir appuyé 2 secondes pour ouvrir le cadenas',
    aide: 'Maintenir appuyé (souris, doigt, ou barre d’espace)',
    enCours: 'Maintien en cours, continuez.',
    tropTot: 'Relâché trop tôt : le cadenas reste fermé.',
    ouvert: 'Cadenas ouvert : vous pouvez changer de classe.',
  },
  profil: {
    titre: 'Profil',
    etat: 'Profil : {profil}',
    question: 'Je suis… (facultatif)',
    note: 'Le profil ne change que la disposition et le nombre de classes. Rien n’est verrouillé.',
    enfant: 'Enfant',
    enfantDesc: 'Une classe, verrouillée par un petit cadenas',
    parent: 'Parent',
    parentDesc: 'Une ou plusieurs classes (plusieurs enfants), fiches toutes prêtes',
    enseignant: 'Enseignant',
    enseignantDesc: 'Plusieurs classes, entrée Programme, lien pour les familles',
  },
  pied: {
    navigation: 'Pied de page',
    programme: 'Programme',
    fichesPretes: 'Fiches toutes prêtes',
    nouveautes: 'Nouveautés',
    apropos: 'À propos',
    signaler: 'Signaler une erreur',
    depot: 'Code sur GitHub',
    contact: 'Contact',
    libre: 'Gratuit · sans publicité · sans cookie ni pistage',
  },
} as const
