// Textes des pages statiques (français) : fiches, index A→Z, page introuvable, écrits dans le HTML au build (scripts/build/statique/).
// Les titres et descriptions viennent du JSON de l'entrée, jamais d'ici. Source des clés : br/textes/statique.ts.
export default {
  accueil: 'Accueil',
  fichesAImprimer: 'Fiches à imprimer',
  filAriane: 'Fil d’Ariane',
  apercu: 'Aperçu de la fiche',
  apercuPage: 'Aperçu, page {n} : {titre}',
  pdf: 'Télécharger le PDF',
  portrait: 'portrait',
  landscape: 'paysage',
  pdfDetail: '{titre} ({format}, {taille})',
  taille: '{n} Ko',
  pages: { one: '{n} page', other: '{n} pages' },
  personnaliser: 'Personnaliser cette fiche',
  enLigne: 'Faire en ligne',
  classes: 'Classes',
  domaine: 'Domaine',
  competences: 'Compétences du programme',
  programmeOfficiel: 'Programme officiel',
  voisines: 'Fiches voisines',
  fiches: 'Fiches à télécharger',
  cadreProgramme: 'Programmes officiels de l’école primaire (Éducation nationale)',
  type: { affiche: 'Affiche à apprendre', fiche: 'Fiche d’exercices', exercice: 'Fiche d’exercices' },
  indexTitre: 'Toutes les fiches à imprimer',
  indexIntro: 'Affiches pour apprendre et fiches pour s’entraîner, en PDF, gratuites et prêtes à imprimer, rangées par matière puis par ordre alphabétique.',
  indexVide: 'Les fiches arrivent bientôt.',
  matiere: { maths: 'Mathématiques', francais: 'Français', monde: 'Le monde', regionale: 'Langue régionale' },
  horsProgramme: 'Autres fiches',
  introuvableTitre: 'Page introuvable',
  introuvableTexte: 'Cette adresse n’existe pas (ou n’existe plus). Tu peux chercher une fiche ou revenir à l’accueil.',
  rechercher: 'Chercher une fiche',
  champ: 'Mot à chercher (alphabet, heure, CE1…)',
  chercher: 'Chercher',
} as const
