// Textes de l'interface — page des fiches à télécharger (/telechargements et la page d'une fiche), français.
// Source des clés : br/textes/telechargements.ts doit avoir exactement les mêmes.
export default {
  titre: 'Fiches à imprimer',
  intro: 'Affiches pour apprendre et fiches pour s’entraîner, en PDF, gratuites et prêtes à imprimer, rangées par domaine du programme.',
  rechercher: 'Rechercher une fiche (alphabet, heure, CE1…)',
  filtres: 'Filtres',
  usage: 'Usage',
  classe: 'Classe',
  langue: 'Langue',
  tout: 'Tout',
  toutes: 'Toutes',
  apprendre: 'Pour apprendre',
  sentrainer: 'Pour s’entraîner',
  compteur: { one: '{n} fiche', other: '{n} fiches' },
  aucune: 'Aucune fiche ne correspond. Essaie un autre mot, ou enlève un filtre.',
  effacer: 'Effacer les filtres',
  chargement: 'Chargement des fiches…',
  vide: 'Il n’y a pas encore de fiche prête à télécharger sur ce site.',
  absent: 'La liste des fiches est introuvable.',
  absentDev: 'En développement, produis-la avec « npm run fiches:dev », puis recharge la page.',
  erreur: 'Les fiches n’ont pas pu être lues : {message}',
  reessayer: 'Réessayer',
  voirRegionale: 'Afficher aussi les fiches en {langue}',
  variantes: { one: '{n} fiche', other: '{n} fiches différentes' },
  pages: { one: '{n} page', other: '{n} pages' },
  retour: 'Toutes les fiches',
  fiche: 'Fiche {n}',
  apercu: 'Aperçu de la fiche',
  page: 'Page {n} sur {total}',
  precedent: 'Précédent',
  suivant: 'Suivant',
  telecharger: 'Télécharger le PDF',
  telechargerFormat: 'Télécharger en {format}',
  imprimer: 'Imprimer',
  imprimerAide: 'Imprime en « taille réelle » (100 %), sans « ajuster à la page ».',
  personnaliser: 'Personnaliser cette fiche',
  personnaliserAide: 'Avec « Personnaliser », tu changes les réglages et tu fais autant de fiches que tu veux.',
  infos: 'Informations',
  formats: 'Papier',
  poids: 'Poids',
  classes: 'Classes',
  langues: 'Langue des fiches',
  domaine: 'Domaine',
  programmeOfficiel: 'programme officiel',
  competences: 'Compétences travaillées',
  sourceProgramme: 'voir le programme, page {page}',
  parCompetence: 'Fiches par compétence',
  parCompetenceAide: 'La fiche ci-dessus mélange toutes les compétences de la classe. Pour en travailler une seule :',
  bilan: 'Toutes les compétences de la classe',
  voisines: 'Autres fiches',
  introuvable: 'Cette fiche n’existe pas (ou plus).',
  exemple: 'exemple',
} as const
