// Textes de l'interface — vocabulaire (français) : la page et le jeu. Source des clés : br/textes/vocabulaire.ts doit avoir exactement les mêmes.
// La fiche est dans le catalogue de contenu (src/exercices/vocabulaire/textes.ts) ; les textes calculés des questions (c_, ex…, sol…, lettreAvant…)
// sont demandés par le générateur avec leur clé seule (`vocabulaire.<clé>`).
export default {
  titre: 'Vocabulaire',
  g_dico: 'Ordre alphabétique et dictionnaire',
  g_sens: 'Le sens des mots',
  g_construction: 'Construction des mots et catégories',
  type_alpha: 'Ranger des mots',
  type_lettre: 'Lettre avant / après',
  type_dictionnaire: 'Mots-repères',
  type_definitions: 'Définitions',
  type_contexte: 'Le sens dans la phrase',
  type_contraires: 'Contraires',
  type_synonymes: 'Mots de même sens',
  type_homonymes: 'Mots qui se disent pareil',
  type_sensFigure: 'Sens propre / figuré',
  type_familles: 'Familles de mots (intrus)',
  type_prefixes: 'Préfixes re-, dé-, in-',
  type_suffixes: 'Suffixes -eur, -ette, -ment…',
  type_categorie: 'Mot étiquette',
  type_intrus: 'Intrus dans une catégorie',
  astuce: 'Tu peux choisir plusieurs exercices : ils seront mélangés.',
  correction: 'Correction',
  c_alpha: "Range les mots dans l'ordre alphabétique.",
  c_lettre: 'Quelle lettre vient juste avant ou juste après ?',
  c_contraires: 'Trouve le contraire.',
  c_synonymes: 'Trouve le mot qui a le même sens (ou presque).',
  c_definitions: 'Quel mot correspond à cette définition ?',
  c_familles: "Trouve l'intrus : le mot qui n'est pas de la même famille.",
  c_categorie: 'Trouve le mot étiquette qui va avec tous ces mots.',
  c_intrus: "Trouve l'intrus : le mot qui ne va pas avec les autres.",
  c_prefixes: 'Quel préfixe faut-il ajouter au début du mot ?',
  c_dictionnaire: 'Dans le dictionnaire, entre quels mots-repères se trouve ce mot ?',
  c_contexte: 'Que veut dire le mot en gras dans cette phrase ?',
  c_homonymes: 'Choisis le mot qui convient.',
  c_sensFigure: 'Le mot en gras est-il employé au sens propre ou au sens figuré ?',
  c_sensFigurePhrase: 'Cette phrase est-elle au sens propre ou au sens figuré ?',
  c_suffixes: 'Quel suffixe faut-il ajouter à la fin du mot ?',
  exAlpha3: 'Les deux premières lettres sont les mêmes : on regarde la 3e lettre.',
  exAlpha2: 'Tous les mots commencent par la même lettre : on regarde la 2e lettre.',
  exAlpha1: 'On regarde la première lettre de chaque mot.',
  lettreAvant: 'Quelle lettre vient juste avant {l} ?',
  lettreApres: 'Quelle lettre vient juste après {l} ?',
  exLettre: "Dans l'alphabet : {a}, {l}, {c}.",
  solAvant: 'Avant {l} : {r} ({a} – {l} – {c})',
  solApres: 'Après {l} : {r} ({a} – {l} – {c})',
  exContraire: '« {r} » est le contraire de « {m} ».',
  exSynonyme: '« {r} » est un mot de même sens que « {m} ».',
  exFamille: "{liste} sont de la famille de « {f} ». « {i} » n'en fait pas partie.",
  solIntrus: '{liste} — intrus : {i}',
  exCategorie: 'Ce sont {e}.',
  exIntrus: '{liste} sont {e}. « {i} » est {un}.',
  solIntrusCat: '{liste} ({e}) — intrus : {i}',
  noteIm: ' On écrit « im » devant m, b, p.',
  exDico: "Dans l'ordre alphabétique : {a} → {m} → {c}.",
  solDico: '{m} : entre {a} et {c}',
  exContexte: 'Ici, « {m} » veut dire : {s}.',
  sensPropre: 'sens propre',
  sensFigure: 'sens figuré',
  fbOrdre: '❌ Le bon ordre est : {r}',
  fbChoix: '❌ La bonne réponse est « {r} »',
  cliqueEtiquettes: "Clique sur les mots dans l'ordre alphabétique…",
} as const
