import { chromium } from 'playwright-core'
const b = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' })
const p = await b.newPage({ viewport: { width: 1100, height: 1300 } })
const err = []; p.on('pageerror', e => err.push(String(e)))
let ouvertures = 0; p.on('popup', () => ouvertures++)
await p.goto('http://localhost:5173/ecole-primaire/#/imprimer'); await p.waitForTimeout(800)
await p.locator('a.card', { hasText: /Calcul mental/ }).first().click(); await p.waitForTimeout(1200)
console.log('URL :', p.url().split('#')[1])
const avant = await p.locator('iframe').getAttribute('srcdoc')
await p.getByRole('button', { name: /Nouvelle fiche/ }).click(); await p.waitForTimeout(500)
const apres = await p.locator('iframe').getAttribute('srcdoc')
console.log('nouvelle fiche différente :', avant !== apres, '| script d\'impression retiré :', !apres.includes('window.print'))
console.log('temps par question masqué en impression :', await p.getByText(/Temps par question/).count() === 0)
await p.screenshot({ path: '/tmp/pw/mode-imprimer.png' })
await p.getByRole('tab', { name: /Faire l'exercice/ }).click(); await p.waitForTimeout(500)
console.log('jouer → URL :', p.url().split('#')[1], '| temps visible :', await p.getByText(/Temps par question/).count() > 0, '| aperçu absent :', await p.locator('iframe').count() === 0)
await p.getByRole('button', { name: /Commencer/ }).click(); await p.waitForTimeout(400)
console.log('jeu lancé :', await p.locator('.exercise-question').count() > 0, '| fenêtres ouvertes :', ouvertures, '| erreurs :', err)
await b.close()
