import { chromium } from 'playwright-core'
const b = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' })
const p = await b.newPage({ viewport: { width: 1100, height: 900 } })
const err = []; p.on('pageerror', e => err.push(String(e)))
await p.goto('http://localhost:5173/ecole-primaire/telechargements/cartes-alphabet-une-lettre-par-page/'); await p.waitForTimeout(500)
console.log('position :', await p.locator('.pager .position').innerText())
await p.locator('.fleche[data-pas="1"]').click(); await p.keyboard.press('ArrowRight'); await p.waitForTimeout(200)
console.log('après ▶ + → :', await p.locator('#pos').innerText(), await p.locator('#apercu').getAttribute('src'))
await p.locator('.fleche[data-pas="-1"]').click(); await p.locator('.fleche[data-pas="-1"]').click(); await p.locator('.fleche[data-pas="-1"]').click()
console.log('après 3 × ◀ :', await p.locator('#pos').innerText())
await p.screenshot({ path: '/tmp/pw/pager.png' })
await p.goto('http://localhost:5173/ecole-primaire/telechargements/affiche-alphabet-breton-a3/'); await p.waitForTimeout(500)
await p.screenshot({ path: '/tmp/pw/alpha-br.png' })
console.log('erreurs :', err)
await b.close()
