import { chromium } from 'playwright-core'
const b = await chromium.launch({ executablePath: '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' })
const p = await b.newPage({ viewport: { width: 1280, height: 900 } })
const err = []; p.on('pageerror', e => err.push(String(e)))
await p.goto('http://localhost:5173/ecole-primaire/#/'); await p.waitForTimeout(800)
await p.keyboard.press('Meta+k'); await p.waitForTimeout(300)
await p.keyboard.type('heure'); await p.waitForTimeout(500)
console.log('« heure » :', await p.locator('.resultats li').allInnerTexts().then(l => l.map(x => x.replace(/\n/g, ' | ').slice(0, 70))))
await p.screenshot({ path: '/tmp/pw/rech.png' })
await p.keyboard.press('Enter'); await p.waitForTimeout(500)
console.log('Entrée →', p.url().split('#')[1])
await p.keyboard.press('/'); await p.keyboard.type('tables ce1'); await p.waitForTimeout(300)
console.log('« tables ce1 » :', await p.locator('.resultats li').count(), 'résultats | erreurs :', err)
await b.close()
