// Les textes de l'affiche de conjugaison, en français seulement (une version bretonne attend un relecteur brittophone), lus avec T(clé) :
//   titre, titreVerbe (le titre de la feuille), variante.<id>.court|titre|description (la convention des affiches ; ceux de `main`),
//   temps.<id> (le nom des temps), legende.* (la légende des couleurs), axe.* (le choix du verbe, puis de la série de temps).
import type { TextesAffiche } from '../types.ts'

export const TEXTES: TextesAffiche = {
  fr: {
    titre: 'Conjugaison',
    titreVerbe: 'Conjuguer le verbe {inf}',
    'temps.present': 'Présent', 'temps.imparfait': 'Imparfait', 'temps.futur': 'Futur', 'temps.passe-compose': 'Passé composé',
    'temps.passe-simple': 'Passé simple', 'temps.plus-que-parfait': 'Plus-que-parfait',
    'legende.radical': 'radical', 'legende.terminaison': 'terminaison', 'legende.aux': 'auxiliaire', 'legende.pp': 'participe passé',
    'legende.auxiliaire': 'verbe auxiliaire', 'legende.groupe': 'verbe du {groupe}',
    'axe.verbe': 'Le verbe', 'axe.temps': 'Les temps',
    'axe.verbe.etre': 'être', 'axe.verbe.avoir': 'avoir', 'axe.verbe.chanter': 'chanter', 'axe.verbe.finir': 'finir', 'axe.verbe.aller': 'aller', 'axe.verbe.faire': 'faire', 'axe.verbe.dire': 'dire', 'axe.verbe.venir': 'venir', 'axe.verbe.pouvoir': 'pouvoir', 'axe.verbe.voir': 'voir', 'axe.verbe.vouloir': 'vouloir', 'axe.verbe.prendre': 'prendre',
    'axe.temps.cycle': 'Présent, imparfait, futur, passé composé', 'axe.temps.cm2': 'Passé simple et plus-que-parfait (CM2)', 'axe.temps.present': 'Le présent seul (CP)',
    'variante.etre.court': "Conjugaison : être",
    'variante.etre.titre': "Conjugaison du verbe être : présent, imparfait, futur, passé composé",
    'variante.etre.description': "Affiche de conjugaison du verbe être au présent, à l'imparfait, au futur et au passé composé de l'indicatif, avec le radical et la terminaison en couleur.",
    'variante.etre-passe-simple.court': "être : passé simple",
    'variante.etre-passe-simple.titre': "Conjugaison du verbe être : passé simple et plus-que-parfait",
    'variante.etre-passe-simple.description': "Affiche de conjugaison du verbe être au passé simple et au plus-que-parfait de l'indicatif (programme du CM2).",
    'variante.avoir.court': "Conjugaison : avoir",
    'variante.avoir.titre': "Conjugaison du verbe avoir : présent, imparfait, futur, passé composé",
    'variante.avoir.description': "Affiche de conjugaison du verbe avoir au présent, à l'imparfait, au futur et au passé composé de l'indicatif, avec le radical et la terminaison en couleur.",
    'variante.avoir-passe-simple.court': "avoir : passé simple",
    'variante.avoir-passe-simple.titre': "Conjugaison du verbe avoir : passé simple et plus-que-parfait",
    'variante.avoir-passe-simple.description': "Affiche de conjugaison du verbe avoir au passé simple et au plus-que-parfait de l'indicatif (programme du CM2).",
    'variante.chanter.court': "Conjugaison : chanter",
    'variante.chanter.titre': "Conjugaison du verbe chanter : présent, imparfait, futur, passé composé",
    'variante.chanter.description': "Affiche de conjugaison du verbe chanter au présent, à l'imparfait, au futur et au passé composé de l'indicatif, avec le radical et la terminaison en couleur.",
    'variante.chanter-passe-simple.court': "chanter : passé simple",
    'variante.chanter-passe-simple.titre': "Conjugaison du verbe chanter : passé simple et plus-que-parfait",
    'variante.chanter-passe-simple.description': "Affiche de conjugaison du verbe chanter au passé simple et au plus-que-parfait de l'indicatif (programme du CM2).",
    'variante.finir.court': "Conjugaison : finir",
    'variante.finir.titre': "Conjugaison du verbe finir : présent, imparfait, futur, passé composé",
    'variante.finir.description': "Affiche de conjugaison du verbe finir au présent, à l'imparfait, au futur et au passé composé de l'indicatif, avec le radical et la terminaison en couleur.",
    'variante.finir-passe-simple.court': "finir : passé simple",
    'variante.finir-passe-simple.titre': "Conjugaison du verbe finir : passé simple et plus-que-parfait",
    'variante.finir-passe-simple.description': "Affiche de conjugaison du verbe finir au passé simple et au plus-que-parfait de l'indicatif (programme du CM2).",
    'variante.aller.court': "Conjugaison : aller",
    'variante.aller.titre': "Conjugaison du verbe aller : présent, imparfait, futur, passé composé",
    'variante.aller.description': "Affiche de conjugaison du verbe aller au présent, à l'imparfait, au futur et au passé composé de l'indicatif, avec le radical et la terminaison en couleur.",
    'variante.aller-passe-simple.court': "aller : passé simple",
    'variante.aller-passe-simple.titre': "Conjugaison du verbe aller : passé simple et plus-que-parfait",
    'variante.aller-passe-simple.description': "Affiche de conjugaison du verbe aller au passé simple et au plus-que-parfait de l'indicatif (programme du CM2).",
    'variante.faire.court': "Conjugaison : faire",
    'variante.faire.titre': "Conjugaison du verbe faire : présent, imparfait, futur, passé composé",
    'variante.faire.description': "Affiche de conjugaison du verbe faire au présent, à l'imparfait, au futur et au passé composé de l'indicatif, avec le radical et la terminaison en couleur.",
    'variante.faire-passe-simple.court': "faire : passé simple",
    'variante.faire-passe-simple.titre': "Conjugaison du verbe faire : passé simple et plus-que-parfait",
    'variante.faire-passe-simple.description': "Affiche de conjugaison du verbe faire au passé simple et au plus-que-parfait de l'indicatif (programme du CM2).",
    'variante.dire.court': "Conjugaison : dire",
    'variante.dire.titre': "Conjugaison du verbe dire : présent, imparfait, futur, passé composé",
    'variante.dire.description': "Affiche de conjugaison du verbe dire au présent, à l'imparfait, au futur et au passé composé de l'indicatif, avec le radical et la terminaison en couleur.",
    'variante.dire-passe-simple.court': "dire : passé simple",
    'variante.dire-passe-simple.titre': "Conjugaison du verbe dire : passé simple et plus-que-parfait",
    'variante.dire-passe-simple.description': "Affiche de conjugaison du verbe dire au passé simple et au plus-que-parfait de l'indicatif (programme du CM2).",
    'variante.venir.court': "Conjugaison : venir",
    'variante.venir.titre': "Conjugaison du verbe venir : présent, imparfait, futur, passé composé",
    'variante.venir.description': "Affiche de conjugaison du verbe venir au présent, à l'imparfait, au futur et au passé composé de l'indicatif, avec le radical et la terminaison en couleur.",
    'variante.venir-passe-simple.court': "venir : passé simple",
    'variante.venir-passe-simple.titre': "Conjugaison du verbe venir : passé simple et plus-que-parfait",
    'variante.venir-passe-simple.description': "Affiche de conjugaison du verbe venir au passé simple et au plus-que-parfait de l'indicatif (programme du CM2).",
    'variante.pouvoir.court': "Conjugaison : pouvoir",
    'variante.pouvoir.titre': "Conjugaison du verbe pouvoir : présent, imparfait, futur, passé composé",
    'variante.pouvoir.description': "Affiche de conjugaison du verbe pouvoir au présent, à l'imparfait, au futur et au passé composé de l'indicatif, avec le radical et la terminaison en couleur.",
    'variante.pouvoir-passe-simple.court': "pouvoir : passé simple",
    'variante.pouvoir-passe-simple.titre': "Conjugaison du verbe pouvoir : passé simple et plus-que-parfait",
    'variante.pouvoir-passe-simple.description': "Affiche de conjugaison du verbe pouvoir au passé simple et au plus-que-parfait de l'indicatif (programme du CM2).",
    'variante.voir.court': "Conjugaison : voir",
    'variante.voir.titre': "Conjugaison du verbe voir : présent, imparfait, futur, passé composé",
    'variante.voir.description': "Affiche de conjugaison du verbe voir au présent, à l'imparfait, au futur et au passé composé de l'indicatif, avec le radical et la terminaison en couleur.",
    'variante.voir-passe-simple.court': "voir : passé simple",
    'variante.voir-passe-simple.titre': "Conjugaison du verbe voir : passé simple et plus-que-parfait",
    'variante.voir-passe-simple.description': "Affiche de conjugaison du verbe voir au passé simple et au plus-que-parfait de l'indicatif (programme du CM2).",
    'variante.vouloir.court': "Conjugaison : vouloir",
    'variante.vouloir.titre': "Conjugaison du verbe vouloir : présent, imparfait, futur, passé composé",
    'variante.vouloir.description': "Affiche de conjugaison du verbe vouloir au présent, à l'imparfait, au futur et au passé composé de l'indicatif, avec le radical et la terminaison en couleur.",
    'variante.vouloir-passe-simple.court': "vouloir : passé simple",
    'variante.vouloir-passe-simple.titre': "Conjugaison du verbe vouloir : passé simple et plus-que-parfait",
    'variante.vouloir-passe-simple.description': "Affiche de conjugaison du verbe vouloir au passé simple et au plus-que-parfait de l'indicatif (programme du CM2).",
    'variante.prendre.court': "Conjugaison : prendre",
    'variante.prendre.titre': "Conjugaison du verbe prendre : présent, imparfait, futur, passé composé",
    'variante.prendre.description': "Affiche de conjugaison du verbe prendre au présent, à l'imparfait, au futur et au passé composé de l'indicatif, avec le radical et la terminaison en couleur.",
    'variante.prendre-passe-simple.court': "prendre : passé simple",
    'variante.prendre-passe-simple.titre': "Conjugaison du verbe prendre : passé simple et plus-que-parfait",
    'variante.prendre-passe-simple.description': "Affiche de conjugaison du verbe prendre au passé simple et au plus-que-parfait de l'indicatif (programme du CM2).",
    'variante.etre-present.court': "être : présent",
    'variante.etre-present.titre': "Conjugaison du verbe être : le présent",
    'variante.etre-present.description': "Affiche de conjugaison du verbe être au présent de l'indicatif, avec le radical et la terminaison en couleur (programme du CP).",
    'variante.avoir-present.court': "avoir : présent",
    'variante.avoir-present.titre': "Conjugaison du verbe avoir : le présent",
    'variante.avoir-present.description': "Affiche de conjugaison du verbe avoir au présent de l'indicatif, avec le radical et la terminaison en couleur (programme du CP).",
  },
}
