// Les textes de l'affiche « La phrase » (français seulement). Les noms des types et des formes (déclarative, négative…) et « verbe » sont
// ceux de l'exercice de grammaire (src/langues/fr/textes/grammaire.ts) : un seul texte pour le même mot, sur l'affiche et dans le jeu.
import type { TextesAffiche } from '../types.ts'

export const TEXTES: TextesAffiche = {
  fr: {
    titre: 'Qu’est-ce qu’une phrase ?',
    'titre.ce1': 'La phrase : ses types, ses formes',
    'variante.definition.court': 'Qu’est-ce qu’une phrase ?',
    'variante.definition.titre': 'Affiche : qu’est-ce qu’une phrase ? Majuscule, point, mots dans l’ordre, un sens',
    'variante.definition.description': 'Ce qui fait une phrase (une majuscule, un point, des mots dans le bon ordre, un sens), et trois exemples de ce qui n’en est pas une.',
    'def.titre': 'Une phrase, c’est…',
    'def.exemple': 'Le chat dort sur le tapis.',
    'def.majuscule': 'une majuscule',
    'def.point': 'un point',
    'def.regle.majuscule': 'Elle commence par une majuscule.',
    'def.regle.point': 'Elle finit par un point ( . ? ! ).',
    'def.regle.ordre': 'Ses mots sont dans le bon ordre.',
    'def.regle.sens': 'Elle veut dire quelque chose.',
    'def.pas.titre': 'Ce n’est pas une phrase',
    'def.pas.ordre': 'Le chat le tapis dort sur.',
    'def.pas.ordre.raison': 'les mots sont dans le désordre',
    'def.pas.majuscule': 'le chat dort sur le tapis',
    'def.pas.majuscule.raison': 'pas de majuscule, pas de point',
    'def.pas.sens': 'Le tapis mange une chanson.',
    'def.pas.sens.raison': 'cela ne veut rien dire',
    'variante.explication.court': 'La phrase expliquée',
    'variante.explication.titre': 'Affiche : la phrase expliquée (CE1) — une suite de mots qui a du sens, majuscule, point, de qui on parle',
    'variante.explication.description': 'Ce qu’est une phrase, les trois choses à vérifier (majuscule, point, sens), une suite de mots qui n’en est pas une, et « de qui on parle, ce qu’on en dit ».',
    'exp.definition': 'Une phrase, c’est une suite de mots qui a du sens.',
    'exp.exemple': 'La petite fille danse avec ses amies.',
    'exp.verifier': 'Pour la reconnaître, je vérifie trois choses :',
    'exp.v.majuscule': 'une majuscule au début',
    'exp.v.point': 'un point à la fin',
    'exp.v.point.detail': '.  ?  !',
    'exp.v.sens': 'du sens',
    'exp.v.sens.detail': 'on comprend',
    'exp.pas.titre': 'Attention : ce n’est pas une phrase',
    'exp.pas.1': 'Le bleu manger demain parapluie.',
    'exp.pas.1.raison': 'une majuscule, un point… mais cela ne veut rien dire',
    'exp.qui.titre': 'Dans une phrase, on dit de qui ou de quoi on parle, et ce qu’on en dit',
    'exp.qui.sujet': 'de qui, de quoi on parle ?',
    'exp.qui.sujet.nom': 'le groupe sujet',
    'exp.qui.reste': 'qu’est-ce qu’on en dit ?',
    'exp.qui.1.sujet': 'La petite fille', 'exp.qui.1.reste': 'danse avec ses amies.',
    'variante.ce1.court': 'La phrase (CE1)',
    'variante.ce1.titre': 'Affiche de la phrase : majuscule et point, types de phrases, formes négative et exclamative',
    'variante.ce1.description': 'Ce qu’est une phrase, ses trois types (déclarative, interrogative, impérative) et leur ponctuation, les formes négative et exclamative, et les groupes de la phrase.',
    'reglage.groupes': 'Les groupes de la phrase',
    'valeur.groupes.true': 'Sujet, verbe, complément',
    'valeur.groupes.false': 'Pas de groupes',
    'regle.titre': 'Une phrase',
    'regle.texte': ': une majuscule, un point ( . ? ! ), du sens.',
    'regle.exemple': 'Le chat dort sur le tapis.',
    'types.titre': 'Les trois types de phrases',
    'type.declarative.role': 'je dis quelque chose',
    'type.declarative.exemple': 'Il fait beau.',
    'type.interrogative.role': 'je pose une question',
    'type.interrogative.exemple': 'Est-ce qu’il fait beau ?',
    'type.imperative.role': 'je donne un ordre, un conseil',
    'type.imperative.exemple': 'Mets ton manteau.',
    'formes.titre': 'Deux formes de phrases',
    'formes.lien': 'Une phrase peut aussi être négative : Ne mets pas ton manteau.',
    'forme.negative.role': 'avec ne … pas',
    'forme.negative.exemple': 'Il ne fait pas beau.',
    'forme.exclamative': 'exclamative',
    'forme.exclamative.role': 'je montre ce que je ressens',
    'forme.exclamative.exemple': 'Comme il fait beau !',
    'groupes.titre': 'Les groupes de la phrase',
    'groupe.sujet': 'groupe sujet',
    'groupe.complement': 'complément',
    'groupe.exemple.sujet': 'La maîtresse',
    'groupe.exemple.verbe': 'raconte',
    'groupe.exemple.complement': 'une histoire.',
    'groupe.question.sujet': 'Qui est-ce qui ?',
  },
}
